version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: produtos_postgres
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_passwd}
      POSTGRES_DB: ${POSTGRES_DB:-db_app_matteo}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
